### ISSUE TITLE
default LLM not available to most users

### ISSUE THREAD

**Issue by lockmeister** [Integuru-AI/Integuru#2]
When I run
poetry run python -m integuru --prompt "download the ..... "

I get an error: 
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `o1-mini` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

As at 29 October 2024, according to https://openai.com/index/openai-o1-mini-advancing-cost-efficient-reasoning/
o1-mini is only available to Tier 5 users https://platform.openai.com/docs/guides/rate-limits/usage-tiers

which will not be many of those trying Integuru.
I recommend setting a default model which is likely to work for the average user trying out Integuru, otherwise many will give up and move on from what otherwise looks like a very promising and interesting tool.

**Comment by lockmeister** [comment]
I tried this command but got the same error
 poetry run python -m integuru --model gpt-4o-mini --prompt "download the...."

error
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `o1-mini` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by alanalanlu** [comment]
please change `o1_llm = ChatOpenAI(model="o1-mini", temperature=1)` in print.py to your model of choice. 

Its hard coded for now as it works the best with o1 models. Ill push a fix to use 4o as fallback.
