### ISSUE TITLE
Jupyter notebook error

### ISSUE THREAD

**Issue by lockmeister** [Integuru-AI/Integuru#3]
Error running cell 2 of main.ipynb

NotFoundError                       Traceback (most recent call last)
Cell In[2], line 2
      1 from typing import List
----> 2 from integration_agent.graph_builder import build_graph
      3 from integration_agent.util.LLM import llm
      4 from dotenv import load_dotenv

ModuleNotFoundError: No module named 'integration_agent'

**Comment by alanalanlu** [comment]
Good catch!
