### ISSUE TITLE
Function calling not supported with o1-preview

### ISSUE THREAD

**Issue by hdashr** [Integuru-AI/Integuru#5]
Hi! I am trying to use the tool with the o1-preview model, running command 

poetry run python -m integuru --prompt "<some prompt>" --generate-code --model o1-preview

openai.BadRequestError: Error code: 400 - {'error': {'message': "Unsupported parameter: 'function_call' is not supported with this model.", 'type': 'invalid_request_error', 'param': 'function_call', 'code': 'unsupported_parameter'}}

**Comment by alanalanlu** [comment]
Function calls are not supported for o1-preview so I would recommend using the default 4o model for the graph generation. The code will automatically use o1-preview if available in your open ai account and use o1-preview for the code generation.
